baseurl = "https://microbialgardens.com"
title = "Microbial Gardens"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
# disableRSS = true
disableKinds=["RSS"]

[params]
  pagetitle = "Microbial Gardens"
  sitetitle = "Microbial Gardens"
  description = 'A living adventure'
  logo = "fa-bug"
  copyright = "Team Microbial Gardens"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1
title = "Dimension"
